/****************************************Copyright (c)****************************************************
**
**                             INNO Instrument(China) Co.Ltd.
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  FieldViewFactory.h
** Latest Version:             V1.0.0
** Latest modified Date:       2017/1/18
** Modified by:                
** Descriptions:               
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 
** Created date:               2017/1/18
** Descriptions:               FieldViewFactory class  [Generated by VP-UML, IGT1.2]
** 
*********************************************************************************************************/
#ifndef __FIELDVIEWFACTORY_H__
#define __FIELDVIEWFACTORY_H__

#include "fieldlibrary_global.h"
// #include "IFieldProxy.h"
// #include "FieldView.h"

class FieldProxy;
class FieldView;
class IField;

/**
 * @class FieldViewFactory
 * @brief 字段视图工厂，用于根据字段来创建字段视图对象
 */
class FIELDLIBRARY_EXPORT FieldViewFactory 
{

public:
    /**
     * Constructor
     */
    FieldViewFactory(FieldProxy* fieldProxy = NULL);
    virtual ~FieldViewFactory();

    /*!
     * Getter/Setter for fieldProxy
     */
    FieldProxy* fieldProxy() const
    {
        return m_fieldProxy;
    }
    void setFieldProxy(FieldProxy* fieldProxy)
    {
        m_fieldProxy = fieldProxy;
    }

public:
    IField* field(QObject* object) const;

    /**
     * 创建一个字段视图
     * @param[in] rootObject  根对象
     * @param[in] createChildren  是否为根对象的子对象创建视图
     * @return       FieldView
     */
    FieldView* createView(QObject* rootObject, bool createChildren = true);


private: 
    FieldProxy* m_fieldProxy;              //!< 用于从某种对象中提取字段对象的代理
};


#endif
/*********************************************************************************************************
** End of file
*********************************************************************************************************/