/****************************************Copyright (c)****************************************************
**
**                             INNO Instrument(China) Co.Ltd.
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  FieldProxy.h
** Latest Version:             V1.0.0
** Latest modified Date:       2017/1/18
** Modified by:                
** Descriptions:               
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 
** Created date:               2017/1/18
** Descriptions:               FieldProxy class  [Generated by VP-UML, IGT1.2]
** 
*********************************************************************************************************/
#ifndef __IFIELDPROXY_H__
#define __IFIELDPROXY_H__

#include "IField.h"

class IField;

/**
 * @class FieldProxy
 * @brief 字段代理接口，用于从某个对象（例如某个端口）中提取字段
 */
class FIELDLIBRARY_EXPORT FieldProxy
{

public:
    /**
     * Constructor
     */
    FieldProxy();

public: 
    /**
     * 从某个对象中提取字段
     * @param[in] object  指定的对象
     * @return       IField
     */
    virtual IField* field(QObject* object) = 0;

    /**
     * 设置某个对象的字段
     * @param[in] object  指定的对象
     * @param[in] field  需要设置到对象的字段
     * @return       bool
     */
    virtual bool setField(QObject* object, IField* field) = 0;
};

Q_DECLARE_INTERFACE(FieldProxy, "com.inno.FieldProxy")

#endif
/*********************************************************************************************************
** End of file
*********************************************************************************************************/