/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i remote_interface.h -p :remote_interface.cpp remote.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "remote_interface.h"
/*
 * Implementation of interface class ComInnoF280RemoteInterface
 */

ComInnoF280RemoteInterface::ComInnoF280RemoteInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComInnoF280RemoteInterface::~ComInnoF280RemoteInterface()
{
}

