/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a remote_adaptor.h: remote.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef REMOTE_ADAPTOR_H_1492156080
#define REMOTE_ADAPTOR_H_1492156080

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.inno.f280.remote
 */
class RemoteAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.inno.f280.remote")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.inno.f280.remote\">\n"
"    <method name=\"writeField\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"role\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"data\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"col\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"readField\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"role\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"col\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"requestAnalyzerStart\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"activityName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"time\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestAnalyzerStop\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestAnalyzerRestart\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"activityName\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"changeSyncSrcMode\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"channel\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestSystemSnapshot\">\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"    </method>\n"
"    <method name=\"requestSystemReboot\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestSystemShutdown\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestSystemRootLogin\">\n"
"      <arg type=\"s\" name=\"code\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestSystemRootLogout\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestFirmwareVersion\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"requestFirmwareUpgrade\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestSystemTime\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"requestSetSystemTime\">\n"
"      <arg type=\"s\" name=\"time\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"requestDeviceID\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"requestGPSStatus\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"storageFileList\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"storageItemCount\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"saveStorageInfo\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"removeStorageInfo\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"loadStorageInfo\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"renameStorageFile\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"storageItemInfo\">\n"
"      <arg type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"emulateMouse\">\n"
"      <arg type=\"i\" name=\"type\"/>\n"
"      <arg type=\"i\" name=\"x\"/>\n"
"      <arg type=\"i\" name=\"y\"/>\n"
"      <arg type=\"i\" name=\"button\"/>\n"
"    </method>\n"
"    <method name=\"emulateKey\">\n"
"      <arg type=\"i\" name=\"type\"/>\n"
"      <arg type=\"i\" name=\"key\"/>\n"
"      <arg type=\"i\" name=\"modifier\"/>\n"
"    </method>\n"
"    <method name=\"emulateTouch\"/>\n"
"    <method name=\"emulateGesture\"/>\n"
"  </interface>\n"
        "")
public:
    RemoteAdaptor(QObject *parent);
    virtual ~RemoteAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool changeSyncSrcMode(int mode, int channel);
    void emulateGesture();
    void emulateKey(int type, int key, int modifier);
    void emulateMouse(int type, int x, int y, int button);
    void emulateTouch();
    bool loadStorageInfo(int index);
    QString readField(const QString &path, const QString &role, int row, int col);
    bool removeStorageInfo(int index);
    bool renameStorageFile(int index, const QString &name);
    bool requestAnalyzerRestart(const QString &activityName);
    bool requestAnalyzerStart(const QString &activityName, const QString &time);
    bool requestAnalyzerStop();
    QString requestDeviceID();
    bool requestFirmwareUpgrade();
    QString requestFirmwareVersion();
    bool requestGPSStatus();
    bool requestSetSystemTime(const QString &time);
    bool requestSystemReboot();
    bool requestSystemRootLogin(const QString &code);
    bool requestSystemRootLogout();
    bool requestSystemShutdown();
    QDBusVariant requestSystemSnapshot();
    QString requestSystemTime();
    bool saveStorageInfo(int index);
    QString storageFileList();
    int storageItemCount();
    QString storageItemInfo(int index);
    bool writeField(const QString &path, const QString &role, const QDBusVariant &data, int row, int col);
Q_SIGNALS: // SIGNALS
};

#endif
