/****************************************Copyright (c)****************************************************
**
**                             INNO Instrument(China) Co.Ltd.
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  IWidgetContainer.cpp
** Latest Version:             V1.0.0
** Latest modified Date:       2017/1/18
** Modified by:                
** Descriptions:               
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 
** Created date:               2017/1/12
** Descriptions:               IWidgetContainer __interface  [Generated by VP-UML, IGT1.2]
** 
*********************************************************************************************************/
#include "includes.h"
#include "IWidgetContainer.h"
#include <QSpacerItem>
IWidgetContainer::IWidgetContainer()
    : m_strenchs()
    , m_spacing(6)
    , m_spacerPosition()
{
}

IWidgetContainer::~IWidgetContainer()
{

}