/****************************************Copyright (c)****************************************************
**
**                             INNO Instrument(China) Co.Ltd.
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  ContainerFieldView.h
** Latest Version:             V1.0.0
** Latest modified Date:       2017/1/18
** Modified by:                
** Descriptions:               
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 
** Created date:               2017/1/13
** Descriptions:               ContainerFieldView class  [Generated by VP-UML, IGT1.2]
** 
*********************************************************************************************************/
#ifndef __CONTAINERFIELDVIEW_H__
#define __CONTAINERFIELDVIEW_H__


// #include "QWidget.h"
#include "FieldView.h"
#include "IWidgetContainer.h"

class QWidget;
// class FieldView;

/**
 * @class ContainerFieldView
 * @brief 字段视图容器，同时也是一种视图，可以容纳一系列子字段视图
 */
class FIELDLIBRARY_EXPORT ContainerFieldView : public FieldView
{
    Q_OBJECT
    Q_PROPERTY(QList<FieldView *> children READ children WRITE setChildren)

public:
    /**
     * Constructor
     */
    ContainerFieldView();

    /*!
     * Getter/Setter for children
     */
    QList<FieldView *> children() const
    {
        return m_children;
    }
    void setChildren(const QList<FieldView *>& children)
    {
        m_children = children;
    }
public:
    /**
     * 先创建IWidgetContainer，然后调用全部子视图的createWidget，并将其逐个添加到自身的IWidgetContainer
     * @return       QWidget
     */
    virtual QObject* createWidget() Q_DECL_OVERRIDE;


private: 
    QList<FieldView*> m_children;           //!< 子字段视图列表
};


#endif
/*********************************************************************************************************
** End of file
*********************************************************************************************************/