# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./FieldProxy.h \
    ./FieldViewFactory.h \
    ./IFieldWidget.h \
    ./IWidgetContainer.h \
    ./DataField_p.h \
    ./FieldLibrary.h \
    ./fieldlibrary_global.h \
    ./QuickFieldWidgetFactory.h \
    ./QuickFieldView.h \
    ./QuickFieldItem.h \
    ./ComWidget.h \
    ./ComContainerWidget.h \
    ./ByteArrayField.h \
    ./FileField.h \
    ./FractionField.h \
    ./VirtualField.h \
    ./View.h \
    ./StringField.h \
    ./RealField.h \
    ./IntegerField.h \
    ./IField.h \
    ./FieldWidgetFactory.h \
    ./FieldView.h \
    ./FieldProxyModel.h \
    ./FieldModel.h \
    ./ContainerFieldView.h \
    ./DataField.h \
    ./EnumField.h \
    $$PWD/FieldWidgetCreator.h \
    $$PWD/MyDoubleValidator.h
SOURCES += ./ByteArrayField.cpp \
    ./ComContainerWidget.cpp \
    ./ComWidget.cpp \
    ./ContainerFieldView.cpp \
    ./EnumField.cpp \
    ./FieldLibrary.cpp \
    ./FieldModel.cpp \
    ./FieldProxy.cpp \
    ./FieldProxyModel.cpp \
    ./FieldView.cpp \
    ./FieldViewFactory.cpp \
    ./FieldWidgetFactory.cpp \
    ./FileField.cpp \
    ./FractionField.cpp \
    ./IField.cpp \
    ./IFieldWidget.cpp \
    ./IntegerField.cpp \
    ./IWidgetContainer.cpp \
    ./QuickFieldItem.cpp \
    ./QuickFieldView.cpp \
    ./QuickFieldWidgetFactory.cpp \
    ./RealField.cpp \
    ./StringField.cpp \
    ./View.cpp \
    ./VirtualField.cpp \
    $$PWD/FieldWidgetCreator.cpp \
    $$PWD/MyDoubleValidator.cpp