/****************************************Copyright (c)****************************************************
**
**                                       D.H. InfoTech
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  Activity.cpp
** Latest Version:             V1.0.0
** Latest modified Date:       2016/3/2
** Modified by:                
** Descriptions:               
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 
** Created date:               2016/2/29
** Descriptions:               Activity class  [Generated by VP-UML, IGT1.0]
** 
*********************************************************************************************************/
#include "includes.h"
#include "common/Activity.h"
#include "IField.h"

bool Activity::start()
{
    m_previousConfig.clear();
    QList<ConfigItem *> items = configItems();
    int itemsCount = items.size();;
    for (int item = 0; item < itemsCount; item++)
    {
        QString path = items[item]->path();
        QVariant data = items[item]->data();
        int role = items[item]->role();

        IField *itemField = IField::at(path);
        if (itemField)
        {
            QVariant previousData = itemField->data();
            m_previousConfig << previousData;
            itemField->setData(-1, -1, data, role);
        }
    }
    return true;
}

bool Activity::stop()
{
    QList<ConfigItem *> items = configItems();
    int itemsCount = items.size();
    for (int item = 0; item < itemsCount; item++)
    {
        QString path = items[item]->path();
        QVariant data = m_previousConfig[item];
        int role = items[item]->role();
        IField *itemField = IField::at(path);
        if (itemField)
        {
            itemField->setData(-1, -1, data, role);
        }
    }
    m_previousConfig.clear();
    return true;
}


/*********************************************************************************************************
** End of file
*********************************************************************************************************/