/****************************************Copyright (c)****************************************************
**
**                                       D.H. InfoTech
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  ClockThread.h
** Latest Version:             V1.0.0
** Latest modified Date:       
** Modified by:
** Descriptions:
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 Wang Longfei
** Created date:               2016/12/30
** Descriptions:               ClockThread class  [Generated by VP-UML, IGT1.0]
**
*********************************************************************************************************/
#pragma once

#include "corelibrary_global.h"
#include <QThread>
#include <QMutex>

class CORELIBRARY_EXPORT ClockThread : public QThread
{
    Q_OBJECT
public:
    ClockThread(QObject *parent = NULL);
    ~ClockThread();

    void setInterrupt();
    bool getInterrupt();
    void resetInterrupt();

private slots:
    void setCurrentTime();

signals:
    void setRequest();

protected:
    void run() Q_DECL_OVERRIDE;
private:
    QMutex m_lock;                          //!< 请求队列安全访问所使用的锁
    bool  m_interrupted;                    //!< 请求中断标志
};

