/****************************************Copyright (c)****************************************************
**
**                                       D.H. InfoTech
**
**--------------File Info---------------------------------------------------------------------------------
** File name:                  IScriptable.cpp
** Latest Version:             V1.0.0
** Latest modified Date:       2016/5/25
** Modified by:                
** Descriptions:               
**
**--------------------------------------------------------------------------------------------------------
** Created by:                 
** Created date:               2016/5/25
** Descriptions:               IScriptable class  [Generated by VP-UML, IGT1.1]
** 
*********************************************************************************************************/
#include "includes.h"
#include "IScriptable.h"

#include "JsonLoader/JsonLoader.h"

/**
 * Constructor
 */
IScriptable::IScriptable()
{
    // TODO: Not yet implemented
}

QObject* IScriptable::newInstance(const QString& typeName)
{
    int typeId = ObjectType::type(typeName.toLatin1().constData());
    if (typeId == QMetaType::UnknownType)
        return NULL;

    void* ptr = ObjectType::create(typeId);
    QObject* object = reinterpret_cast<QObject*>(ptr);

    return object;
}

bool IScriptable::deleteInstance(QObject* instance)
{
    if (instance)
    {
        delete instance;
        return true;
    }

    return false;
}

/*********************************************************************************************************
** End of file
*********************************************************************************************************/